#!/bin/sh

# Please be careful to keep this file sh compatible

if [ "${ABI}" ]; then
	abi=${ABI}
elif [ "${DEFAULT_ABI}" ]; then
	abi=${DEFAULT_ABI}
else 
	# we're called from outside portage, so use the hardcoded abi list
	hardcoded_abis="PLACEHOLDER_FOR_HARDCODED_ABIS"
	for abi in ${hardcoded_abis}; do
		[ -f "${0}-${abi}" ] && break
		abi=
	done
fi

if [ -f "${0}-${abi}" ]; then
	exec "${0}-${abi}" ${1+"$@"}
else
	if [ -L "${0}" ]; then
		LINK_TARGET="$(readlink "${0}")"
		exec "${LINK_TARGET}" ${1+"$@"}
	else
		echo "${0}: abi-wrapper couldn't find an executable for current abi ${abi}" >&2
		exit 1
	fi
fi
