#!/bin/bash

if [[ -n ${ABI} ]]; then
	abi=${ABI}
elif [[ -n ${DEFAULT_ABI} ]]; then
	abi=${DEFAULT_ABI}
else 
	# we're called from outside portage, so use the hardcoded abi list
	hardcoded_abis=="PLACEHOLDER_FOR_HARDCODED_ABIS"
	for abi in ${hardcoded_abis}; do
		[[ -f ${0}-${abi} ]] && break
		unset abi
	done
fi

if [[ -f ${0}-${abi} ]]; then
	exec ${0}-${abi} "${@}"
else
	if [[ -L ${0} ]]; then
		LINK_TARGET="$(readlink ${0})"
		exec ${LINK_TARGET} "${@}"
	else
		echo "${0}: abi-wrapper couldn't find an executable for current abi ${abi}" >&2
		exit 1
	fi
fi
